add signup.ejs and a signup button in sidebar.ejs
sristy17/MindDrive pull request #11
Opened 2024-10-01 08:38 UTC by theCodeCrusaderX

![1](https://github.com/user-attachments/assets/9981c8d0-f87b-46b6-b296-7d5e2e40698d)
![2](https://github.com/user-attachments/assets/68f219c4-406e-4f80-ab79-e2b8666bac4b)
![opensource0](https://github.com/user-attachments/assets/67cea6a0-6df5-4cb6-820e-33ba0512d987)

as it my first contribution i want some feedback from u ,

i did not able to add user using postman and even using browser as it is restricted by u .

i have add the image that what exactly i am getting while registering the user .

is this ok or i need or i implemented wrong 

waiting for your feedback

2024-10-01 08:46 UTC, pooranjoyb commented
lemme check the permissions for mongodb.

2024-10-01 10:18 UTC, theCodeCrusaderX commented
yupp!! signup is working well from my end 

![11](https://github.com/user-attachments/assets/2ab82422-5abc-42d4-964e-5d59effc8d3e)

once the user click signup button the user info is being stored in db check that one 

one more thing do i need to protect all the route as till now it only signup the user

2024-10-01 16:07 UTC, pooranjoyb requested changes

2024-10-01 16:07 UTC, pooranjoyb commented on views/pages/Signup.ejs
okay so there are few changes that you need to make.

- Use packages like [Toastify](https://apvarun.github.io/toastify-js/#) for response messages.
- Donot redirect and show response like this.

![image](https://github.com/user-attachments/assets/76c70299-dd2b-4042-a653-810df695903b)

- Create the SignUp redirection in the Avatar itself and NOT a separate button.

![image](https://github.com/user-attachments/assets/ab44fd13-656f-4032-9586-55bdb3d1470a)

- Also make sure you maintain the Theme and Color, Please have a look onto this, please.

2024-10-02 04:00 UTC, theCodeCrusaderX commented on views/pages/Signup.ejs
Ok thanks for feedback 😃

2024-10-02 05:15 UTC, theCodeCrusaderX commented
![2 10 14](https://github.com/user-attachments/assets/6e61b12b-ef9e-4fe9-82c0-1e68c911b57e)


did the changes that you wnated have a look from your side too...

completed signup form .

2024-10-02 07:56 UTC, theCodeCrusaderX commented
Please check it so then I will work on login form too...

2024-10-02 08:32 UTC, pooranjoyb requested changes

2024-10-02 08:32 UTC, pooranjoyb commented on views/includes/sidebar.ejs
> +        <button class="p-3 rounded-lg border">Signup</button>
Remove this button as we are navigating using the Avatar icon.

2024-10-02 08:34 UTC, pooranjoyb requested changes

2024-10-02 08:34 UTC, pooranjoyb commented on views/pages/profile.ejs
> +    <title>About</title>
Change this to Profile

2024-10-02 08:35 UTC, pooranjoyb commented
I guess that's all, Probably ready to merge. @theCodeCrusaderX

2024-10-02 08:47 UTC, merged