Dark toggle theme button added
sristy17/MindDrive pull request #27
Opened 2024-10-02 05:51 UTC by mahenoorsalat

**Pull request : Add Toggle Button Functionality**

- Fixes issue #5 

- [x] Added a toggle button in the HTML that allows users to show or hide the content dynamically.
- [x] Created a .hidden CSS class to control the visibility of the content when the toggle button is clicked.
- [x] Updated the JavaScript to include an event listener for the toggle button, enabling the content to be hidden or displayed based on user interaction.

**Let me know if any other touch are needed! Thank you 👍**

Ping @sristy17

2024-10-02 06:49 UTC, sristy17 commented
> **Pull request : Add Toggle Button Functionality**
> 
> * Fixes issue [UI: Light/Dark Mode #5](https://github.com/sristy17/MindDrive/issues/5)
> * [x]  Added a toggle button in the HTML that allows users to show or hide the content dynamically.
> * [x]  Created a .hidden CSS class to control the visibility of the content when the toggle button is clicked.
> * [x]  Updated the JavaScript to include an event listener for the toggle button, enabling the content to be hidden or displayed based on user interaction.
> 
> **Let me know if any other touch are needed! Thank you 👍**
> 
> Ping @sristy17

Dark mode is not working in the home page of mobile version fix it please. Rest all looks fine

2024-10-02 08:45 UTC, pooranjoyb requested changes

2024-10-02 08:45 UTC, pooranjoyb commented on views/pages/about.ejs
> +  <script>
Donot write scripts in the `views` files. We are maintaining a proper directory structure. Please write the scripts in `public/js` directory and link them in `views`

2024-10-02 08:45 UTC, pooranjoyb commented on views/pages/index.ejs
> +    <style>
Same thing please donot write styles in the `views` files. We are maintaining a proper directory structure. Please write the scripts in `public/css` directory and link them in `views`

2024-10-02 08:45 UTC, pooranjoyb commented on views/pages/index.ejs
> +<script>
should be in `public/js`

2024-10-02 08:47 UTC, mahenoorsalat commented on views/pages/index.ejs
> +<script>
okay will  add there @pooranjoyb

2024-10-02 08:50 UTC, pooranjoyb commented
also take a pull and resolve conflicts @mahenoorsalat

2024-10-02 15:57 UTC, pooranjoyb commented
Please resolve conflicts 👍🏼  @mahenoorsalat

2024-10-03 04:35 UTC, pooranjoyb requested changes

2024-10-03 04:35 UTC, pooranjoyb commented on app.js
Why did you remove the database connection method? @mahenoorsalat

2024-10-03 13:44 UTC, sristy17 commented
Hey, just a small change 
![Screenshot from 2024-10-03 19-12-02](https://github.com/user-attachments/assets/78404ba2-35ec-4398-b006-bf93fc87d144)
Make the bg-colour of the home page shade lighter like the others. 

![Screenshot from 2024-10-03 19-14-06](https://github.com/user-attachments/assets/1f0c4629-1127-40b7-83a2-d4eeb1581b06)
The bg-colour you applied for all looks good.

2024-10-03 13:50 UTC, pooranjoyb commented
- Also make sure the cards of youtube are not in light mode, make them compatible to dark mode too* @mahenoorsalat

2024-10-04 04:41 UTC, pooranjoyb commented
commits of this PR is also available in #39 right? @mahenoorsalat

2024-10-04 05:36 UTC, mahenoorsalat commented
yeah it is!

2024-10-05 06:35 UTC, pooranjoyb commented
this has a lotta conflicts, closing this one. Please create a new PR

2024-10-05 06:35 UTC, closed without merging