[FEATURE] Auth Management #33
sristy17/MindDrive pull request #38
Opened 2024-10-03 16:24 UTC by theCodeCrusaderX

all the functionality that you wanted is done .

one more thing that u wanted session based auth so its being new to me but somehow due to doc i manage to do with session based auth thats why it took little bit more time if i will be doing as jwt and it would be easier for me but i challenge myself and did this 

![image](https://github.com/user-attachments/assets/f17c77e0-3998-4d75-bb63-2702e1b14a10)

one more thing i added a extra route for logout i know i can be done without doing this but belive me its good practice deling logout feature using saparate route . and also its being easy for me to clear the session after the user logout.

thats all thank u for giving me this opportunity.

2024-10-03 17:14 UTC, pooranjoyb commented
Please resolve the conflicts.

2024-10-04 01:41 UTC, theCodeCrusaderX commented
now check

2024-10-04 06:18 UTC, theCodeCrusaderX commented
ahh.. all conflicts are resolved now you can merge it

2024-10-04 16:42 UTC, theCodeCrusaderX commented
is everything ok ? when you will merge :)

2024-10-05 05:00 UTC, pooranjoyb commented
> is everything ok ? when you will merge :)

Some minor conflicts, fix them, else all fine. will merge

2024-10-05 06:26 UTC, theCodeCrusaderX commented
done

2024-10-05 06:34 UTC, pooranjoyb requested changes
also i cannot see the user data in the Cookies after the Successful login :/

2024-10-05 06:34 UTC, pooranjoyb commented on views/pages/profile.ejs
> +  <!-- handeling form data -->
You removed the Auth.js file. please check that script should be kept in /js/ folder in public dir

2024-10-05 14:10 UTC, closed without merging