[BUG] Disparities in font colors in Darkmode #57 is Fixed
sristy17/MindDrive pull request #64
Opened 2024-12-14 21:08 UTC by Archi-shaw

@pooranjoyb . Please review it.
Fixes issue #57

2024-12-15 06:43 UTC, sristy17 commented
> @pooranjoyb . Please review it. Fixes issue #57

![Screenshot from 2024-12-15 12-12-33](https://github.com/user-attachments/assets/a711775b-8d95-4188-81d1-2935a94c5d34)
I cannot see any changes in the backgound? :/

2024-12-15 06:49 UTC, sristy17 commented
> @pooranjoyb . Please review it. Fixes issue #57

Fix the backgound colour as well in the dark mode, font colour is fine.

2024-12-15 14:02 UTC, pooranjoyb requested changes
Yes, font color looks fine, just change the modal BG similar to the card's BG (when in darkmode)

Have a look on this,
https://github.com/sristy17/MindDrive/blob/41da97b71c59c4dd322dd0b580948d4931f9152f/public/js/global.js#L113

@Archi-shaw

2024-12-20 06:34 UTC, pooranjoyb commented
@Archi-shaw status?

2024-12-20 08:01 UTC, Archi-shaw commented
Working will create pr by Tuesday.

2024-12-25 09:01 UTC, sristy17 commented
@Archi-shaw any updates?

2024-12-25 10:30 UTC, Archi-shaw commented
@sristy17  Sorry for the inconvenience, as I was quite bussy for a few days. I will surely raise pr by 28th Dec.

2024-12-25 10:49 UTC, sristy17 commented
> @sristy17 Sorry for the inconvenience, as I was quite bussy for a few days. I will surely raise pr by 28th Dec.

sure np

2024-12-28 17:09 UTC, sristy17 commented
![Screenshot from 2024-12-28 22-37-56](https://github.com/user-attachments/assets/1ad35241-1130-4850-bdac-61fc9030e073)
@Archi-shaw just make the bg solid instead this image cz this trobbles in reading the texts also make the size of the modal box bit shorter in length

2024-12-28 17:11 UTC, sristy17 commented on public/js/global.js
> +        modalbackground.style.height = 'auto';
set height

2024-12-28 17:12 UTC, sristy17 commented on public/css/modal.css
> +    /* background-image: url('../images/greyish-bg.png'); */
set bg colour instead something greyish and make the text color lighter

2025-01-10 12:20 UTC, closed without merging

2025-01-10 12:20 UTC, sristy17 commented
Closing as stale