Implement darkmode functionality in /profile route
sristy17/MindDrive pull request #79
Opened 2024-12-29 14:36 UTC by wildcraft958

## Fixes Issue

Closes #52

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

i have completed the feature implementationa s required using inline js script and some css

2024-12-29 16:56 UTC, sristy17 commented
@wildcraft958 its all good looks very fine but in dark mode bg is dark and modal box is light and vice versa in light mode can you just change that make both dark or both light.?

2024-12-29 16:59 UTC, sristy17 requested changes
@wildcraft958  its all good looks very fine but in dark mode bg is dark and modal box is light and vice versa in light mode can you just change that make both dark or both light.?

2024-12-29 17:37 UTC, wildcraft958 commented
![image](https://github.com/user-attachments/assets/08606227-a4b1-4676-af70-82273a247ae7)
![Screenshot from 2024-12-29 23-06-31](https://github.com/user-attachments/assets/31f664a8-7eaa-466e-9035-09211a32c6fa)
i guess this works?

2024-12-29 17:39 UTC, wildcraft958 commented
![Screenshot from 2024-12-29 23-06-31](https://github.com/user-attachments/assets/28089219-34b9-42e1-8f69-f7c2b4a01d89)

2024-12-31 07:07 UTC, pooranjoyb commented
I guess you didn't fix the `SignIn` part?

![image](https://github.com/user-attachments/assets/07eae45d-36ae-4c2d-a021-310e8f9621c7)

@wildcraft958

2024-12-31 19:50 UTC, wildcraft958 commented
@pooranjoyb bug has been fixed please review

2025-01-03 15:54 UTC, pooranjoyb commented
Major Changes has been made by the maintainers (including code-fixes & ui-changes). Take a latest pull from `kwoc-2024` and raise a PR. Closing this as there are many conflicts ://

Please check that, **dark-mode will not work on any pages**, you can add the dark-mode to the Login/Signup Page.

@wildcraft958

2025-01-03 15:54 UTC, closed without merging